languageCode = "en"
languageName = "English"
weight = 1
title = "0x8c"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo-clear.png"
secondaryLogo = "logo-clear.png"
description = "Hi, my name is tiff. I am a former frontend engineer pivoting to cybersecurity & malware analysis. i'm also passionate about home labs and devops."

[author]
name = "tiff"
links = [ { email = "gentle.job7737@fastmail.com" }, { github = "https://github.com/twhite96" }, { linkedin = "https://linkedin.com/in/0x8c" }, { mastodon = "https://infosec.exchange/@tiff" }, { pgpkey = "https://www.0x8c.org/t_keys.asc" }, { rss = "https://0x8c.org/feed" }, { youtube = "https://www.youtube.com/@duvallhacks" } ]
image = "author-pic.jpeg"
bio = "Hi, my name is tiff. I am a former frontend developer pivoting to cybersecurity."
