[[main]]
name = "Stuff I like"
weight = 50

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "WwckNRpSHM"
weight = 10

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "projects"
weight = 20

[[main]]
name = "Books"
parent = "Stuff I like"
pageRef = "reading-list"
identifier = "miL6VyrCTd"
weight = 50

[[main]]
name = "Articles"
parent = "Stuff I like"
pageRef = "article-list"
identifier = "vndkdlgok"
weight = 40

# [[main]]
# name = "Archives"
# pageRef = "archives"
# identifier = "ZUAML9G4TT"
# weight = 40

[[main]]
name = "About"
url = "https://about.0x8c.org"
identifier = "aboutpage"
weight = 70

[[main]]
name = "Workbook"
url = "https://workbook.0x8c.org"
identifier = "wiki"
weight = 60

[[footer]]
name = "Notes"
pre = "lightbulb"
url = "https://notes.0x8c.org"

[[footer]]
name = "Code Blog"
pre = "code"
url = "https://tiff.engineer"

[[footer]]
name= "Mastodon"
pre = "mastodon"
url = "https://infosec.exchange/@tiff"

[[footer]]
name = "GitHub"
pre = "github"
url = "https://github.com/twhite96"

[[footer]]
name = "LinkedIn"
pre = "linkedin"
url = "https://linkedin.com/in/tiff0x8c"