[[main]]
name = "Random"
weight = 50

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "WwckNRpSHM"
weight = 10

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "projects"
weight = 20

[[main]]
name = "Books"
parent = "Random"
pageRef = "reading-list"
identifier = "miL6VyrCTd"
weight = 50

# [[main]]
# name = "Archives"
# pageRef = "archives"
# identifier = "ZUAML9G4TT"
# weight = 40

[[main]]
name = "About"
url = "https://about.0x8c.org"
identifier = "aboutpage"
weight = 70

[[main]]
name = "Write-ups"
url = "https://htb-writeups.0x8c.org"
identifier = "htbWriteups"
weight = 50

[[main]]
name = "Wiki"
url = "https://wiki.0x8c.org"
identifier = "wiki"
weight = 60

[[footer]]
name = "Uses"
pre = "code"
url = "uses.tiff.tools"

[[footer]]
name = "Notes"
pre = "lightbulb"
url = "https://notes.0x8c.org"

[[footer]]
name = "Mastodon"
pre = "mastodon"
url = "https://infosec.exchange/@tiff"

[[footer]]
name = "GitHub"
pre = "github"
url = "https://github.com/twhite96"

[[footer]]
name = "LinkedIn"
pre = "linkedin"
url = "https://linkedin.com/in/tiffanyrwhite"