[[main]]
name = "Posts"
pageRef = "posts"
identifier = "WwckNRpSHM"
weight = 1

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "projects"
weight = 2

[[main]]
name = "Books"
parent = "Stuff I like"
pageRef = "reading-list"
identifier = "miL6VyrCTd"
weight = 4

[[main]]
name = "Articles"
parent = "Stuff I like"
pageRef = "article-list"
identifier = "vndkdlgok"
weight = 3

[[main]]
name = "About"
url = "https://about.0x8c.org"
identifier = "aboutpage"
weight = 7

[[main]]
name = "Workbook"
url = "https://workbook.0x8c.org"
identifier = "wiki"
weight = 6

[[main]]
name = "Project Repos"
url = "https://projects.0x8c.run/explore/repos"
identifier = "rvr2HEF9J3"
weight = 8

[[main]]
name = "Notes"
url = "https://notes.0x8c.org"
identifier = "4w8RnjvXbH"
weight = 9999

[[footer]]
name = "Code Blog"
pre = "codeberg"
url = "https://tiff.engineer"

[[footer]]
name = "Mastodon"
pre = "mastodon"
url = "https://infosec.exchange/@tiff"

[[footer]]
name = "GitHub"
pre = "github"
url = "https://github.com/twhite96"

[[footer]]
name = "LinkedIn"
pre = "linkedin"
url = "https://linkedin.com/in/tiff0x8c"

[[footer]]
name = "Book Notes"
url = "https://reading-notes.0x8c.mobi"
pre = "edit"
identifier = "9XTDOtOuC1"
weight = 9999
